services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ecommerce
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - spring
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  eureka-server:
    image: cihandsz/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE= docker
    networks:
      - spring
    depends_on:
      - zipkin
  api-gateway:
    image: cihandsz/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE= docker
    networks:
      - spring
    depends_on:
      - zipkin
      - eureka-server
  cart-service:
    image: cihandsz/cart-service:latest
    container_name: cart-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE= docker
    networks:
      - spring
      - postgres
    depends_on:
      - eureka-server
      - zipkin
      - postgres
      - rabbitmq
  category-service:
    image: cihandsz/category-service:latest
    container_name: category-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE= docker
    networks:
      - spring
      - postgres
    depends_on:
      - eureka-server
      - zipkin
      - postgres
      - rabbitmq
  inventry-service:
    image: cihandsz/inventry-service:latest
    container_name: inventry-service
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE= docker
    networks:
      - spring
      - postgres
    depends_on:
      - eureka-server
      - zipkin
      - postgres
      - rabbitmq
  notification-service:
    image: cihandsz/notification-service:latest
    container_name: notification-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE= docker
    networks:
      - spring
      - postgres
    depends_on:
      - eureka-server
      - zipkin
      - postgres
      - rabbitmq
  order-service:
    image: cihandsz/order-service:latest
    container_name: order-service
    ports:
      - "8086:8086"
    environment:
      - SPRING_PROFILES_ACTIVE= docker
    networks:
      - spring
      - postgres
    depends_on:
      - eureka-server
      - zipkin
      - postgres
      - rabbitmq
  product-service:
    image: cihandsz/product-service:latest
    container_name: product-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE= docker
    networks:
      - spring
      - postgres
    depends_on:
      - eureka-server
      - zipkin
      - postgres
      - rabbitmq
  user-service:
    image: cihandsz/user-service:latest
    container_name: user-service
    ports:
      - "8087:8087"
    environment:
      - SPRING_PROFILES_ACTIVE= docker
    networks:
      - spring
      - postgres
    depends_on:
      - eureka-server
      - zipkin
      - postgres
      - rabbitmq



networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge
volumes:
  postgres:
  pgadmin: