services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      -spring
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  eureka-server:
    image: cihandsz/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      -SPRING_PROFILES_ACTIVE=docker
    networks:
      -spring
    depends_on: zipkin
  api-gateway:
    image: cihandsz/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      -SPRING_PROFILES_ACTIVE=docker
    networks:
      -spring
    depends_on:
      - zipkin
      - eureka-server
networks:
  spring:
    driver: bridge