server:
  port: 8087
spring:
  application:
    name: user-service
  datasource:
    password: password
    url: jdbc:postgresql://postgres:5432/user-service
    username: ecommerce
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  zipkin:
    base-url: http://zipkin:9411
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

