server:
  port: 8084
spring:
  application:
    name: product-service
  datasource:
    password: password
    url: jdbc:postgresql://postgres:5432/product-service
    username: ecommerce
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  zipkin:
    base-url: http://zipkin:9411
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true

